-- ============================================================
-- CHINOOK MUSIC STORE — SQL DATA ANALYSIS
-- Author: Ranim
-- Database: Chinook (SQLite / PostgreSQL / MySQL compatible)
-- Description: Business-focused SQL queries for portfolio
-- ============================================================


-- ============================================================
-- SECTION 1: SALES & REVENUE ANALYSIS
-- ============================================================

-- Q1. What is the total revenue generated by the store?
SELECT 
    ROUND(SUM(Total), 2) AS total_revenue
FROM Invoice;


-- Q2. Which countries generate the most revenue?
SELECT 
    BillingCountry AS country,
    COUNT(InvoiceId) AS total_orders,
    ROUND(SUM(Total), 2) AS total_revenue
FROM Invoice
GROUP BY BillingCountry
ORDER BY total_revenue DESC
LIMIT 10;


-- Q3. What are the monthly sales trends?
-- (SQLite compatible date format)
SELECT 
    STRFTIME('%Y-%m', InvoiceDate) AS month,
    COUNT(InvoiceId) AS number_of_invoices,
    ROUND(SUM(Total), 2) AS monthly_revenue
FROM Invoice
GROUP BY month
ORDER BY month;


-- Q4. Which invoice had the highest total?
SELECT 
    InvoiceId,
    CustomerId,
    InvoiceDate,
    BillingCountry,
    ROUND(Total, 2) AS invoice_total
FROM Invoice
ORDER BY Total DESC
LIMIT 5;


-- Q5. What is the average order value?
SELECT 
    ROUND(AVG(Total), 2) AS average_order_value
FROM Invoice;


-- ============================================================
-- SECTION 2: TRACK & GENRE PERFORMANCE
-- ============================================================

-- Q6. Which genres are purchased the most?
SELECT 
    g.Name AS genre,
    COUNT(il.InvoiceLineId) AS total_purchases,
    ROUND(SUM(il.UnitPrice * il.Quantity), 2) AS total_revenue
FROM InvoiceLine il
JOIN Track t ON il.TrackId = t.TrackId
JOIN Genre g ON t.GenreId = g.GenreId
GROUP BY g.Name
ORDER BY total_purchases DESC;


-- Q7. What are the top 10 best-selling tracks?
SELECT 
    t.Name AS track_name,
    ar.Name AS artist,
    g.Name AS genre,
    COUNT(il.InvoiceLineId) AS times_purchased,
    ROUND(SUM(il.UnitPrice * il.Quantity), 2) AS revenue
FROM InvoiceLine il
JOIN Track t ON il.TrackId = t.TrackId
JOIN Album al ON t.AlbumId = al.AlbumId
JOIN Artist ar ON al.ArtistId = ar.ArtistId
JOIN Genre g ON t.GenreId = g.GenreId
GROUP BY t.TrackId, t.Name, ar.Name, g.Name
ORDER BY times_purchased DESC
LIMIT 10;


-- Q8. Which media type generates the most revenue?
SELECT 
    mt.Name AS media_type,
    COUNT(il.InvoiceLineId) AS total_sales,
    ROUND(SUM(il.UnitPrice * il.Quantity), 2) AS total_revenue
FROM InvoiceLine il
JOIN Track t ON il.TrackId = t.TrackId
JOIN MediaType mt ON t.MediaTypeId = mt.MediaTypeId
GROUP BY mt.Name
ORDER BY total_revenue DESC;


-- Q9. How many tracks does each artist have in the store?
SELECT 
    ar.Name AS artist,
    COUNT(t.TrackId) AS total_tracks
FROM Track t
JOIN Album al ON t.AlbumId = al.AlbumId
JOIN Artist ar ON al.ArtistId = ar.ArtistId
GROUP BY ar.Name
ORDER BY total_tracks DESC
LIMIT 10;


-- ============================================================
-- SECTION 3: CUSTOMER BEHAVIOUR
-- ============================================================

-- Q10. Who are the top 10 customers by total spend?
SELECT 
    c.CustomerId,
    c.FirstName || ' ' || c.LastName AS customer_name,
    c.Country,
    ROUND(SUM(i.Total), 2) AS total_spend
FROM Customer c
JOIN Invoice i ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, customer_name, c.Country
ORDER BY total_spend DESC
LIMIT 10;


-- Q11. How much has each customer spent on average per invoice?
SELECT 
    c.FirstName || ' ' || c.LastName AS customer_name,
    COUNT(i.InvoiceId) AS number_of_orders,
    ROUND(SUM(i.Total), 2) AS total_spend,
    ROUND(AVG(i.Total), 2) AS avg_per_order
FROM Customer c
JOIN Invoice i ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, customer_name
ORDER BY avg_per_order DESC
LIMIT 10;


-- Q12. Which customers have made only one purchase?
SELECT 
    c.FirstName || ' ' || c.LastName AS customer_name,
    c.Email,
    c.Country,
    COUNT(i.InvoiceId) AS number_of_orders
FROM Customer c
JOIN Invoice i ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, customer_name, c.Email, c.Country
HAVING number_of_orders = 1;


-- Q13. Revenue breakdown by customer country
SELECT 
    c.Country,
    COUNT(DISTINCT c.CustomerId) AS total_customers,
    COUNT(i.InvoiceId) AS total_orders,
    ROUND(SUM(i.Total), 2) AS total_revenue,
    ROUND(AVG(i.Total), 2) AS avg_order_value
FROM Customer c
JOIN Invoice i ON c.CustomerId = i.CustomerId
GROUP BY c.Country
ORDER BY total_revenue DESC;


-- ============================================================
-- SECTION 4: EMPLOYEE PERFORMANCE
-- ============================================================

-- Q14. Which sales support agent has generated the most revenue?
SELECT 
    e.EmployeeId,
    e.FirstName || ' ' || e.LastName AS employee_name,
    e.Title,
    COUNT(DISTINCT c.CustomerId) AS customers_managed,
    ROUND(SUM(i.Total), 2) AS total_revenue_generated
FROM Employee e
JOIN Customer c ON e.EmployeeId = c.SupportRepId
JOIN Invoice i ON c.CustomerId = i.CustomerId
WHERE e.Title = 'Sales Support Agent'
GROUP BY e.EmployeeId, employee_name, e.Title
ORDER BY total_revenue_generated DESC;


-- Q15. How many customers does each employee manage?
SELECT 
    e.FirstName || ' ' || e.LastName AS employee_name,
    e.Title,
    COUNT(c.CustomerId) AS customers_managed
FROM Employee e
LEFT JOIN Customer c ON e.EmployeeId = c.SupportRepId
GROUP BY e.EmployeeId, employee_name, e.Title
ORDER BY customers_managed DESC;


-- ============================================================
-- BONUS: ADVANCED QUERIES
-- ============================================================

-- Q16. Rank customers by spend using window functions
-- (Works in SQLite 3.25+, PostgreSQL, MySQL 8+)
SELECT 
    c.FirstName || ' ' || c.LastName AS customer_name,
    c.Country,
    ROUND(SUM(i.Total), 2) AS total_spend,
    RANK() OVER (ORDER BY SUM(i.Total) DESC) AS spend_rank
FROM Customer c
JOIN Invoice i ON c.CustomerId = i.CustomerId
GROUP BY c.CustomerId, customer_name, c.Country
ORDER BY spend_rank;


-- Q17. Running total of monthly revenue
SELECT 
    STRFTIME('%Y-%m', InvoiceDate) AS month,
    ROUND(SUM(Total), 2) AS monthly_revenue,
    ROUND(SUM(SUM(Total)) OVER (ORDER BY STRFTIME('%Y-%m', InvoiceDate)), 2) AS running_total
FROM Invoice
GROUP BY month
ORDER BY month;


-- Q18. Which genre is most popular per country?
-- Using a subquery to find the top genre per billing country
SELECT 
    country,
    genre,
    total_purchases
FROM (
    SELECT 
        i.BillingCountry AS country,
        g.Name AS genre,
        COUNT(il.InvoiceLineId) AS total_purchases,
        RANK() OVER (
            PARTITION BY i.BillingCountry 
            ORDER BY COUNT(il.InvoiceLineId) DESC
        ) AS genre_rank
    FROM InvoiceLine il
    JOIN Track t ON il.TrackId = t.TrackId
    JOIN Genre g ON t.GenreId = g.GenreId
    JOIN Invoice i ON il.InvoiceId = i.InvoiceId
    GROUP BY i.BillingCountry, g.Name
)
WHERE genre_rank = 1
ORDER BY country;
